# Engineering Math 

session 2 – Gaussian Elimination for **Any Shape**  
Interactive notebook (Python 3)  
Author: 

## 🔧 Setup
```bash
pip install numpy matplotlib
```

## 1️⃣ Gaussian Elimination (row-echelon, any m×n)

In [15]:
import numpy as np

In [20]:
def row_echelon_form(A: np.ndarray) -> np.ndarray:
    """
    Return the row-echelon form of A via Gaussian elimination
    with *partial pivoting* (largest-magnitude pivot in current column).
    """
    A = A.astype(float, copy=True)
    m, n = A.shape
    row = 0

    for col in range(n):
        # 1. Pivot row
        piv = np.argmax(np.abs(A[row:, col])) + row
        if abs(A[piv, col]) < 1e-12:
            continue                      # skip this column (all zeros)

        A[[row, piv]] = A[[piv, row]]

        # 2. Eliminate below pivot
        for i in range(row + 1, m):
            factor = A[i, col] / A[row, col]
            A[i, col:] -= factor * A[row, col:]

        row += 1
        if row == m:
            break
    return A

## 2️⃣ Quick Demo

In [22]:
A = np.array([[2, 1, -1, 8],
              [-3, -1, 2, -11],
              [-2, 1, 2, -3]], float)
REF = row_echelon_form(A)
print("Row-echelon form:\n", REF)

Row-echelon form:
 [[ -3.          -1.           2.         -11.        ]
 [  0.           1.66666667   0.66666667   4.33333333]
 [  0.           0.           0.2         -0.2       ]]


## 3️⃣ Optional: Utility to print pivots & rank

In [ ]:
def pivots_and_rank(REF: np.ndarray, tol: float = 1e-12):
    non_zero = ~np.all(np.isclose(REF, 0.0, atol=tol), axis=1)
    rank = np.sum(non_zero)
    piv_cols = [np.where(np.abs(r) > tol)[0][0] for r in REF[non_zero]]
    return piv_cols, rank

piv_cols, rank = pivots_and_rank(REF)
print("Pivot columns:", piv_cols)
print("Rank:", rank)

## 4️⃣ Reduced Row-Echelon Form (RREF)

In [23]:
def rref(A: np.ndarray) -> np.ndarray:
    """Reduced row-echelon form (RREF) via Gauss-Jordan."""
    A = row_echelon_form(A)
    m, n = A.shape

    for r in range(m - 1, -1, -1):
        # find pivot column
        piv_col = np.where(np.abs(A[r]) > 1e-12)[0]
        if len(piv_col) == 0:
            continue
        piv_col = piv_col[0]
        # make pivot 1
        A[r, :] /= A[r, piv_col]
        # eliminate above
        for k in range(r):
            A[k, :] -= A[k, piv_col] * A[r, :]
    return A

In [24]:
A_rref = rref(A.copy())
print("RREF:\n", A_rref)

RREF:
 [[ 1. -0. -0.  2.]
 [ 0.  1.  0.  3.]
 [ 0.  0.  1. -1.]]


## 5️⃣ Cheat-Sheet

| Task | One-liner |
|------|-----------|
| **REF** (Gaussian elimination) | `row_echelon_form(A)` |
| **RREF** (Reduced Row-Echelon Form) | `rref(A)` |
| **Rank** | `rank = row_echelon_form(A).sum(~np.allclose(..., 0, axis=1))` |

> All functions are **pure NumPy** and work for any **m × n** matrix.